services:
  _defaults:
    public: true

  ##############
  # Your Module

  ec_seo.module:
    class: ec_seo
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'ec_seo'

  ec_seo.context:
    class: Context
    factory: ['Context', 'getContext']

  #####################
  # PrestaShop Account
  ec_seo.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '5.0'

  ec_seo.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@ec_seo.ps_accounts_installer'
  #####################
  # PrestaShop Billing

  ec_seo.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
    - '@ec_seo.ps_accounts_facade'
    - '@ec_seo.context'
    - true # if true, enables the sandbox mode, if false or empty, disables it

  ec_seo.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
    - '@ec_seo.ps_billings_context_wrapper'
    - '@ec_seo.module'

  # Remove this if you do not need BillingService
  ec_seo.ps_billings_service:
    class: 'PrestaShopCorp\Billing\Services\BillingService'
    public: true
    arguments:
    - '@ec_seo.ps_billings_context_wrapper'
    - '@ec_seo.module'